"""Add Client model

Revision ID: 28b1675df50f
Revises:
Create Date: 2025-08-11 02:30:45.229006

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision = '28b1675df50f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('google_oauth_id', sa.String(length=128), nullable=True),
    sa.Column('is_subscribed', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('google_oauth_id')
    )
    op.create_table('business_profile',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('business_name', sa.String(length=120), nullable=False),
    sa.Column('service_area', sa.String(length=200), nullable=False),
    sa.Column('specialties', sa.Text(), nullable=True),
    sa.Column('google_api_key', sqlalchemy_utils.types.encrypted.encrypted_type.EncryptedType(), nullable=True),
    sa.Column('gemini_api_key', sqlalchemy_utils.types.encrypted.encrypted_type.EncryptedType(), nullable=True),
    sa.Column('google_account_id', sa.String(length=128), nullable=True),
    sa.Column('google_location_id', sa.String(length=128), nullable=True),
    sa.Column('google_ads_customer_id', sa.String(length=128), nullable=True),
    sa.Column('campaign_status', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('client',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('business_profile_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('job_description', sa.Text(), nullable=True),
    sa.Column('job_completion_date', sa.Date(), nullable=True),
    sa.Column('follow_up_sent_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['business_profile_id'], ['business_profile.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('client')
    op.drop_table('business_profile')
    op.drop_table('user')
    # ### end Alembic commands ###
