"""Initial migration with user subscriptions

Revision ID: d0ed6453be9a
Revises:
Create Date: 2025-08-11 01:48:54.209368

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd0ed6453be9a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('google_oauth_id', sa.String(length=128), nullable=True),
    sa.Column('is_subscribed', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('google_oauth_id')
    )
    op.create_table('business_profile',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('business_name', sa.String(length=120), nullable=False),
    sa.Column('service_area', sa.String(length=200), nullable=False),
    sa.Column('specialties', sa.Text(), nullable=True),
    sa.Column('google_api_key', sa.String(length=256), nullable=True),
    sa.Column('gemini_api_key', sa.String(length=256), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('business_profile')
    op.drop_table('user')
    # ### end Alembic commands ###
